from __future__ import annotations

from contextlib import contextmanager
from datetime import datetime, timedelta
import json
from typing import Any, Iterator, Mapping
import uuid

import psycopg
from psycopg.rows import dict_row

from .domain import DeliveryConflict, DeliveryState
from .repository import CURRENT_SCHEMA_VERSION, FleetRepository, _now


_SCHEMA_LOCK_ID = 726_710_001


class _Connection:
    """Small DB-API dialect bridge for the shared repository operations."""

    def __init__(self, connection: psycopg.Connection[dict[str, Any]]) -> None:
        self._connection = connection

    @staticmethod
    def _sql(statement: str) -> str:
        normalized = statement.strip()
        if normalized == "BEGIN IMMEDIATE":
            return "SELECT 1"
        statement = statement.replace("?", "%s")
        if "INSERT OR IGNORE INTO printer_operation_leases" in statement:
            statement = statement.replace("INSERT OR IGNORE", "INSERT")
            statement += " ON CONFLICT (printer_id) DO NOTHING"
        return statement

    def execute(self, statement: str, parameters: Any = None):
        return self._connection.execute(self._sql(statement), parameters)


class PostgresFleetRepository(FleetRepository):
    """PostgreSQL adapter with the same observable contract as SQLite Fleet."""

    def __init__(self, database_url: str) -> None:
        self.database_url = database_url

    @contextmanager
    def _connection(self) -> Iterator[_Connection]:
        with psycopg.connect(self.database_url, row_factory=dict_row) as connection:
            yield _Connection(connection)

    def initialize(self) -> None:
        with psycopg.connect(self.database_url, row_factory=dict_row) as db:
            db.execute("SELECT pg_advisory_xact_lock(%s)", (_SCHEMA_LOCK_ID,))
            db.execute(
                """CREATE TABLE IF NOT EXISTS fleet_schema_metadata (
                       singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
                       version INTEGER NOT NULL
                   )"""
            )
            row = db.execute(
                "SELECT version FROM fleet_schema_metadata WHERE singleton = TRUE"
            ).fetchone()
            if row and int(row["version"]) > CURRENT_SCHEMA_VERSION:
                raise RuntimeError(
                    f"Fleet database schema {row['version']} is newer than supported "
                    f"version {CURRENT_SCHEMA_VERSION}"
                )
            schema = """CREATE TABLE IF NOT EXISTS printers (
                    id TEXT PRIMARY KEY, revision INTEGER NOT NULL,
                    payload_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS deliveries (
                    id TEXT PRIMARY KEY, idempotency_key TEXT NOT NULL UNIQUE,
                    request_hash TEXT NOT NULL,
                    printer_id TEXT NOT NULL REFERENCES printers(id),
                    printer_snapshot_json TEXT NOT NULL, route_snapshot_json TEXT,
                    artifact_checksum TEXT NOT NULL, artifact_mime_type TEXT NOT NULL,
                    artifact_payload BYTEA, artifact_description TEXT NOT NULL DEFAULT 'PrintHub job',
                    state TEXT NOT NULL, attempt_count INTEGER NOT NULL DEFAULT 0,
                    max_attempts INTEGER NOT NULL DEFAULT 3, next_attempt_at TEXT,
                    downstream_job_id TEXT, downstream_state TEXT,
                    bytes_accepted INTEGER NOT NULL DEFAULT 0, error TEXT,
                    created_at TEXT NOT NULL, updated_at TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS delivery_events (
                    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    delivery_id TEXT NOT NULL REFERENCES deliveries(id), state TEXT NOT NULL,
                    detail TEXT, occurred_at TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS agents (
                    id TEXT PRIMARY KEY, base_url TEXT NOT NULL UNIQUE, available INTEGER NOT NULL,
                    payload_json TEXT NOT NULL, last_seen_at TEXT, last_error TEXT,
                    updated_at TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS agent_devices (
                    agent_id TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
                    device_id TEXT NOT NULL, payload_json TEXT NOT NULL, observed_at TEXT NOT NULL,
                    PRIMARY KEY(agent_id, device_id)
                );
                CREATE TABLE IF NOT EXISTS printer_observations (
                    printer_id TEXT PRIMARY KEY REFERENCES printers(id) ON DELETE CASCADE,
                    media_json TEXT, alignment_json TEXT, capabilities_json TEXT,
                    source TEXT NOT NULL, observed_at TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS printer_operation_leases (
                    printer_id TEXT PRIMARY KEY REFERENCES printers(id) ON DELETE CASCADE,
                    owner TEXT NOT NULL, kind TEXT NOT NULL, acquired_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS printer_controls (
                    printer_id TEXT PRIMARY KEY REFERENCES printers(id) ON DELETE CASCADE,
                    paused INTEGER NOT NULL DEFAULT 0, reason TEXT, updated_at TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS audit_records (
                    id TEXT PRIMARY KEY, correlation_id TEXT NOT NULL, actor TEXT NOT NULL,
                    method TEXT NOT NULL, path TEXT NOT NULL, status_code INTEGER NOT NULL,
                    occurred_at TEXT NOT NULL
                );
                CREATE INDEX IF NOT EXISTS audit_records_time_idx
                    ON audit_records(occurred_at, id)"""
            for statement in schema.split(";"):
                if statement.strip():
                    db.execute(statement)
            db.execute(
                """INSERT INTO fleet_schema_metadata(singleton, version) VALUES (TRUE, %s)
                   ON CONFLICT(singleton) DO UPDATE SET version=excluded.version""",
                (CURRENT_SCHEMA_VERSION,),
            )

    def create_delivery(
        self,
        *,
        idempotency_key: str,
        request_hash: str,
        printer_id: str,
        printer_snapshot: Mapping[str, Any],
        route_snapshot: Mapping[str, Any],
        artifact_checksum: str,
        artifact_mime_type: str,
        artifact_payload: bytes,
        artifact_description: str,
        max_attempts: int,
        accepted_at: str | None = None,
    ) -> tuple[dict[str, Any], bool]:
        now = accepted_at or _now()
        delivery_id = str(uuid.uuid4())
        with self._connection() as db:
            inserted = db.execute(
                """INSERT INTO deliveries(
                   id, idempotency_key, request_hash, printer_id, printer_snapshot_json,
                   route_snapshot_json, artifact_checksum, artifact_mime_type,
                   artifact_payload, artifact_description, state, max_attempts,
                   next_attempt_at, created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                   ON CONFLICT (idempotency_key) DO NOTHING
                   RETURNING *""",
                (
                    delivery_id, idempotency_key, request_hash, printer_id,
                    json.dumps(dict(printer_snapshot), sort_keys=True),
                    json.dumps(dict(route_snapshot), sort_keys=True), artifact_checksum,
                    artifact_mime_type, artifact_payload, artifact_description,
                    DeliveryState.QUEUED.value, max_attempts, now, now, now,
                ),
            ).fetchone()
            if inserted is None:
                existing = db.execute(
                    "SELECT * FROM deliveries WHERE idempotency_key = ?", (idempotency_key,)
                ).fetchone()
                if existing["request_hash"] != request_hash:
                    raise DeliveryConflict("Idempotency key was reused for another delivery")
                return self._delivery(existing), False
            db.execute(
                "INSERT INTO delivery_events(delivery_id, state, occurred_at) VALUES (?, ?, ?)",
                (delivery_id, DeliveryState.QUEUED.value, now),
            )
        return self._delivery(inserted), True

    def claim_delivery(
        self, delivery_id: str, *, now: str, lease_expires_at: str | None = None
    ) -> dict[str, Any] | None:
        with self._connection() as db:
            row = db.execute(
                "SELECT * FROM deliveries WHERE id = ? FOR UPDATE", (delivery_id,)
            ).fetchone()
            if row is None:
                raise KeyError(delivery_id)
            if row["state"] not in {
                DeliveryState.QUEUED.value, DeliveryState.RETRY_SCHEDULED.value
            } or row["artifact_payload"] is None:
                return None
            if row["next_attempt_at"] and row["next_attempt_at"] > now:
                return None
            blocking = db.execute(
                """SELECT 1 FROM deliveries
                   WHERE printer_id = ? AND id != ? AND artifact_payload IS NOT NULL
                     AND (state IN (?, ?) OR
                         (state IN (?, ?) AND (created_at < ? OR (created_at = ? AND id < ?))))
                   LIMIT 1""",
                (
                    row["printer_id"], delivery_id, DeliveryState.CONNECTING.value,
                    DeliveryState.TRANSMITTING.value, DeliveryState.QUEUED.value,
                    DeliveryState.RETRY_SCHEDULED.value, row["created_at"],
                    row["created_at"], delivery_id,
                ),
            ).fetchone()
            if blocking is not None:
                return None
            expires_at = lease_expires_at or (
                datetime.fromisoformat(now) + timedelta(minutes=5)
            ).isoformat()
            owner = self._try_acquire_operation(
                db, printer_id=str(row["printer_id"]), kind="delivery",
                now=now, expires_at=expires_at,
            )
            if owner is None:
                return None
            db.execute(
                """UPDATE deliveries SET state=?, attempt_count=attempt_count+1,
                   next_attempt_at=NULL, updated_at=? WHERE id=?""",
                (DeliveryState.CONNECTING.value, now, delivery_id),
            )
            db.execute(
                "INSERT INTO delivery_events(delivery_id, state, occurred_at) VALUES (?, ?, ?)",
                (delivery_id, DeliveryState.CONNECTING.value, now),
            )
            claimed = db.execute("SELECT * FROM deliveries WHERE id=?", (delivery_id,)).fetchone()
        result = self._delivery_internal(claimed)
        result["_operation_owner"] = owner
        return result
